#! /usr/bin/env bash
export PASSWORD_STORE_DIR=~/.password-store

function .pass.env {
  # local entries=$1
  local environment

  while [ $# -gt 0 ]; do
    local entry=$1
    shift
    if [ "$entry" = "--" ]; then
      break
    elif [ -f "$PASSWORD_STORE_DIR/env/$entry.gpg" ]; then
      environment="$environment $(pass show env/$entry)"
    else
      environment="$environment $(pass show $entry)"
    fi
  done

  if [ $# -gt 0 ]; then
    (eval export $environment && exec "$@")
  else
    (eval export $environment; exec printenv)
  fi
}
