#! /bin/bash
function .ps1.colorize {
  echo -e "\033[38;5;$1m$2\033[0m"
}


function .ps1.separator {
  echo -e "$(.ps1.colorize 8 $1)"
}


function .ps1.label {
  echo -e "$(.ps1.colorize $1 $2)$(.ps1.separator :)"
}


function .ps1.git_branch {
  local branch=$(git branch 2> /dev/null | awk 'BEGIN { FS="[ (]+" } { if ($1 == "*") print $2; }')
  local rev=$(git rev-parse --short HEAD 2> /dev/null)
  local status_lines=$(git status --porcelain 2> /dev/null | grep '^ [DM]' | wc -l)

  if [[ $status_lines -gt 0 ]]; then
    branch=$(.ps1.colorize 3 $branch)
    rev=$(.ps1.colorize 3 $rev)
  fi

  if [ -z $branch ]; then return; fi
  echo -e " $(.ps1.separator \|) $(.ps1.label 5 git)$branch$(.ps1.separator @)$rev"
}


function .ps1.login {
  echo -e "$(.ps1.colorize 4 "\\u")$(.ps1.separator @)$(.ps1.colorize 4 "\\h")"
}


function .ps1.cwd {
  echo "\w"
}


function .ps1.prompt {
  echo -e "$(.ps1.separator \$) "
}


function .ps1.time {
  echo -e "$(.ps1.colorize 2 $(date "+%H:%M:%S"))"
}

export PS1="\$(.ps1.time) $(.ps1.separator \|) $(.ps1.cwd) $(.ps1.separator \|) $(.ps1.login)\$(.ps1.git_branch)\n$(.ps1.prompt)"
