#! /bin/bash
function .venv {
  if [ $# -eq 1 ]; then
    if [ "$1" == "destroy" ]; then
      deactivate
      rm -rf .venv
      return 0
    fi
    cd $1
  fi

  name=$(basename `pwd`)
  location='./.venv'

  if [ ! -d $location ]; then
    pyenv exec virtualenv --prompt='$name | ' $location
  fi

  source $location/bin/activate
}


function .venv.exec {
  $SHELL -c "source .venv/bin/activate; exec $*"
}


function .venv.pip {
  .venv.exec pip "$@"
}


if [ -z "$PYENV_ROOT" ]; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
fi
