#! /bin/bash
export VIRTUAL_ENV_DISABLE_PROMPT=1

function .venv {
  if [ $# -eq 1 ]; then
    if [ "$1" == "destroy" ]; then
      deactivate
      rm -rf .venv
      return 0
    fi
    cd $1
  fi

  name=$(basename `pwd`)
  location='./.venv'

  if [ ! -d $location ]; then
    virtualenv $location
  fi

  source $location/bin/activate
}


function .venv.exec {
  $SHELL -c "source .venv/bin/activate; exec $*"
}


function .venv.pip {
  .venv.exec pip "$@"
}
