#! /bin/bash
function .ssh.agent {
  local agent_env="$HOME/.ssh/agent"
  if { ! source $agent_env || ! kill -0 $SSH_AGENT_PID; } &> /dev/null; then
    eval `ssh-agent | tee $agent_env` > /dev/null
  fi
}


.ssh.agent
